Avoid setting PBR properties when they are not found on mtl file
assimp/assimp pull request #4440
Opened 2022-03-11 21:34 UTC by sacereda

This comes from https://github.com/assimp/assimp/issues/4424.

Metallic/roughness/sheen/clearcoat properties should only be added to the material if they appear on .mtl file.

Pinging @errissa here, feel free to suggest/change if you find anything odd.

2022-03-14 15:11 UTC, errissa commented
I’ll leave it to the core developers to comment, if necessary, on the implementation details. However, the concept expressed with this PR to optionally add the PBR properties based on their presence in the MTL file makes sense to me and shouldn’t impact anyone using a PBR workflow with OBJ.

2022-03-16 07:37 UTC, kimkulling requested changes
Just 2 small findings. Would you be able to solve these things? When done I will merge it. And maybe you can consider using std::optional? 

Just a question from my side.

2022-03-16 07:37 UTC, kimkulling commented on code/Common/Maybe.h
> +#pragma once
Copyright is missing

2022-03-16 07:37 UTC, kimkulling commented on code/Common/Maybe.h
> +template <typename T>
Documentation is missing

2022-03-16 12:00 UTC, sacereda commented
Sure, I can check. I'm not really versed with std::optional, never used it before, and just tried to use something similar to STEPFile.h::Maybe, in case you were all used to this.

But yes, I can change it if you prefer to use std.

2022-03-16 12:24 UTC, turol commented
`std::optional` is C++17. What do we want our minimum standard requirement to be?

2022-04-12 09:12 UTC, kimkulling approved these changes
Adding the documentation will be added.

2022-04-13 08:11 UTC, merged

2022-04-13 08:12 UTC, kimkulling commented
Merged, thanks a lot for your contribution.