Added support for more bone weights in GLTF2
assimp/assimp pull request #4453
Opened 2022-03-17 19:01 UTC by Promit

The GLTF2 importer doesn't actually read beyond the first four bone weights (first attribute). This patch expands the parser to read as many bone weights as are available in the file.

2022-04-01 02:21 UTC, Promit commented on code/AssetLib/glTF2/glTF2Importer.cpp
> +    Weights **weights = new Weights*[attr.weight.size()];
I agree, I'm going to rewrite it with vectors.

2022-04-19 09:45 UTC, kimkulling requested changes

2022-04-19 09:45 UTC, kimkulling commented on code/AssetLib/glTF2/glTF2Importer.cpp
> +    Weights **weights = new Weights*[attr.weight.size()];
Any progress regarding your approach using std::vector?

2022-04-19 09:45 UTC, kimkulling commented on code/AssetLib/glTF2/glTF2Importer.cpp
> +                    map[bone].reserve(8);
Use of magic number.

2022-08-16 18:54 UTC, kimkulling commented on code/AssetLib/glTF2/glTF2Importer.cpp
> +    Weights **weights = new Weights*[attr.weight.size()];
I guess I will take care.

2022-08-16 18:54 UTC, kimkulling approved these changes

2022-08-16 19:20 UTC, merged

2022-08-16 19:20 UTC, kimkulling commented
Merged, thanks a lot for your contribution.