Fix warnings that are causing build fails with specific build flags
assimp/assimp pull request #4632
Opened 2022-07-08 16:22 UTC by enginmanap

These changes are all minor changes that are aimed to fix warnings.

1) -Werror=ignored-qualifiers
2) -Werror=implicit-fallthrough
3) -Werror=deprecated-copy
4) -Werror=non-virtual-dtor

I am getting them with the following settings:
-std=c++14 -Wall -Wextra -Wnon-virtual-dtor -pedantic

I searched for a coding guide to verify these flags are valid for Assimp project, but couldn't find anything. As far as I can think of, they should not cause any negative effects, and all should be net positives, but if I missed something please let me know.

2022-07-08 21:47 UTC, enginmanap commented
Hey there,

I added 2 commits, they were meant to be seperate PRs, but they somehow got in to this one.
These are:
1) don't force -03 on debug builds, instead use -g.
2) Fix collada import fails on Mixamo models. This one is cause by a leading empty space on vcount tag, which is read as 0. Fixes #4551

If combined PRs are not accepted, I can try to seperate them, please let me know.

2022-07-09 08:00 UTC, kimkulling requested changes
Thanks a lot for your contribution. There are some small findings. I will merge your PR when their are done!

2022-07-09 08:00 UTC, kimkulling commented on code/AssetLib/MMD/MMDPmxParser.h
> +        virtual ~PmxMorphOffset() {
Shall be default destructor.

2022-07-09 15:27 UTC, enginmanap commented on code/AssetLib/Collada/ColladaParser.cpp
> +                            printf("wohoo");
it is, I missed it.

2022-07-09 15:27 UTC, enginmanap commented on code/AssetLib/MMD/MMDPmxParser.h
> +        virtual ~PmxMorphOffset() {
its fixed now.

2022-07-10 11:05 UTC, enginmanap commented
This change also fixes #4363

I assume same goes for 4535, but there is no model in that issue to test, so can't verify.

2022-07-24 21:36 UTC, enginmanap commented
Hey @kimkulling , can you take another look at the PR?

2022-07-27 02:32 UTC, jinfagang commented
Please merge this PR, it very useful.

2022-07-29 18:43 UTC, kimkulling approved these changes
Looks fine!

2022-07-29 19:20 UTC, merged

2022-07-29 19:20 UTC, kimkulling commented
Merged, thanks for your contribution.