Introduce VRML format (.wrl and .x3dv) 3D model support
assimp/assimp pull request #5857
Opened 2024-11-02 03:13 UTC by tellypresence

Closes #5862 

### Overview
Introduce support for loading `.wrl` and `.x3dv` 3D model files.

X3D is a superset of the WRL/X3DV formats.  X3D migrated to `xml` file format, while WRL uses `VRML97` format and X3DV uses "classic VRML" format.  X3D is able to fully understand the content of the older files, on the condition that the formatting is converted from "classic VRML"/`VRML97` to `.xml` format.  Once converted, the file contents as `.xml` are able to be used with the extant X3D importer to load WRL/X3DV files.

### Technical details
_Summary_
Use a mature 3rd party tool to convert WRL/X3DV files on-the-fly to X3D (xml), then simply hand over to the X3D importer as usual.

_Details_
Leveraging the `Scanner` and `Parser` from the mature 3rd party [`meshlab`](https://github.com/cnr-isti-vclab/meshlab/tree/main/src/meshlabplugins/io_x3d/vrml) which provide the ability to load a `.wrl` (`VRML97`) or `.x3dv` ("classic VRML") file and convert on-the-fly from the respective old format to an X3D `.xml` file.

`X3DImporter` is modified to first check whether input file extension is either of `wrl` or `x3dv`, and in this case convert to X3D `.xml` via `Parser`, which provides an in-memory X3D xml file, which can then be handed to a new template override of the `XMLParser::parse()` accepting `std::istream`.

From that point, the common X3D importer code flow is followed regardless of whether the model originated as a native X3D `.xml` file or was converted on the fly from `VRML97` (`.wrl`) or "classic VRML" (`.x3dv`) format.

### Screenshots
The result seems to be satisfactory, basic mesh geometry for fairly complex models appear to be dealt with reasonably correctly.  Some models found "in the wild" have correct normals when imported, some end up with incorrect normals.

#### Models with correct normals

<table>
<tr><th rowspan=2>Model</th><th colspan=2>Screenshots</th><th rowspan=2>Notes</th></tr>
<tr><th>Diffuse lighting</th><th>Debug normals<br>X = Red, Y = Green, Z = Blue</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models/WRL/Wuson.wrl"><tt>test/models/WRL/Wuson.wrl</tt></a></td><td><img src="https://github.com/user-attachments/assets/0b0f7d0b-d9fa-474e-be54-68aa032969cf" alt="Wuson_wrl" width=320 /></td><td><img src="https://github.com/user-attachments/assets/f7d57776-35d2-45c0-933f-01a0aa4eacee" alt="Wuson_wrl_debug_normals" width=320 /></td><td></td></tr>
<tr><td><a href="https://www.artec3d.com/3d-models/borderlands-cosplayer"><tt>Borderlands cosplayer</tt></a></td><td><img src="https://github.com/user-attachments/assets/7c800d35-b4ff-426b-bb34-f31a7c55082d" alt="Borderlands cosplay-wrl" width=90 /><img src="https://github.com/user-attachments/assets/4b3db093-415c-4b7b-ad55-62143c73f380" alt="Borderlands cosplay-wrl" width=90 /></td><td><img src="https://github.com/user-attachments/assets/918a502b-dd1d-4dbc-b769-2b578fab1840" alt="Borderlands cosplay-wrl_debug_normals" width=90 /><img src="https://github.com/user-attachments/assets/f26a2889-eb9a-44c2-b5e8-6c9647b38a53" alt="Borderlands cosplay-wrl_debug_normals" width=90 /></td><td></td></tr>
<tr><td><a href="https://www.artec3d.com/3d-models/harley-quinn-cosplayer"><tt>Harley Quinn cosplayer</tt></a></td><td><img src="https://github.com/user-attachments/assets/f2dc4724-7f3f-49c7-859b-c0cdd34654c1" alt="Harley Quinn-wrl" width=90 /><img src="https://github.com/user-attachments/assets/f8551fec-a98f-434c-98ef-337baffb373d" alt="Harley Quinn-wrl" width=90 /></td><td><img src="https://github.com/user-attachments/assets/bca1d9e8-e5ab-42ba-92a6-93bf5f6c7ffe" alt="Harley Quinn-wrl_debug_normals" width=90 /><img src="https://github.com/user-attachments/assets/a355be18-19e4-4b5d-bd5e-60294be26a68" alt="Harley Quinn-wrl_debug_normals" width=90 /></td><td></td></tr>
<tr><td><a href="https://www.cgtrader.com/free-3d-print-models/art/scans-replicas/3dprint-statue-of-a-sailor"><tt>statue of a sailor</tt></a></td><td><img src="https://github.com/user-attachments/assets/5c066190-952d-4b94-b60d-27870b34b0d7" alt="cgtrader_sailor_w_binoculars_wrl" width=90 /></td><td><img src="https://github.com/user-attachments/assets/c9c2f238-0c10-4e07-b06d-02521334a3d1" alt="cgtrader_sailor_w_binoculars_wrl_debug_normals_ok" width=90 /></td><td></td></tr>

</table>

#### Models with incorrect normals
<table>
<tr><th rowspan=2>Model</th><th colspan=2>Screenshots</th><th rowspan=2>Notes</th></tr>
<tr><th>Diffuse lighting</th><th>Debug normals<br>X = Red, Y = Green, Z = Blue</th></tr>
<tr><td><a href="https://github.com/assimp/assimp/blob/master/test/models/WRL/MotionCaptureROM.WRL"><tt>test/models/WRL/MotionCaptureROM.WRL</tt></a></td><td><img src="https://github.com/user-attachments/assets/ca9cf302-bf28-4ccc-a897-f9225a1cb939" alt="MotionCaptureROM_wrl" width=320 /></td><td><img src="https://github.com/user-attachments/assets/d7027f96-ab07-45ae-9f14-d2f548ee7f19" alt="MotionCaptureROM_wrl_debug_normals" width=90 /></td><td></td></tr>
<tr><td><a href="https://grabcad.com/library/brabham-bt62-2019-1"><tt>BRABHAM BT62 2019</tt></a></td><td><img src="https://github.com/user-attachments/assets/fa7334af-6b62-482b-8860-4c86327e5ec5" alt="brabham-bt62-2019_wrl" width=320 /></td><td><img src="https://github.com/user-attachments/assets/653755fd-6589-4ba3-89ff-c621775db1a1" alt="brabham-bt62-2019_wrl_debug_normals" width=320 /></td><td></td></tr>
<tr><td><a href="https://downloadfree3d.com/3d-models/vehicles/car/mclaren-senna-2019/"><tt>McLaren SENNA 2019</tt></a></td><td><img src="https://github.com/user-attachments/assets/79fed8ea-f03a-4cd8-91c7-d9169b80c3c9" alt="mclaren-senna-2019_wrl" width=90 /><img src="https://github.com/user-attachments/assets/29f44f92-e7e9-41b0-8ea2-2b6973d2f8ad" alt="mclaren-senna-2019_wrl" width=320 /></td><td><img src="https://github.com/user-attachments/assets/966a6c1c-a290-407c-a7f2-5338470bcf07" alt="mclaren-senna-2019_wrl_debug_normals" width=90 /><img src="https://github.com/user-attachments/assets/d54cc755-d0e6-4789-ba8c-ad6a985c1da7" alt="mclaren-senna-2019_wrl_debug_normals" width=320 /></td><td></td></tr>

</table>

### Caveats
- Note that the X3D importer is currently in a broken state, as detailed in
  - #4992
   Since the WRL/X3DV model file is simply convered to an X3D `.xml` file, the result will only be as good as the `X3DImporter`.

- Normals are correct for some, and incorrect for other `.wrl` models tested, but probably better to get this feature into the hands of users and investigate problems later (could be the models themselves have bad normals)

### Issues related to this PR
This PR addresses one of the formats requested in #3145

2024-11-02 20:16 UTC, tellypresence commented
@kimkulling Please review when you have time, this PR provides the ability to load `.wrl` files which wasn't possible previously.

2024-11-09 19:28 UTC, tellypresence commented
Seems like most of the Sonar Cloud notices are related to code copied from the 3rd party external `meshlab` project, or advocating for C++17 features (e.g. replacing `const std::string&` w/`std::string_view`), wondering if it will be okay to ignore those and merge this PR anyway

2024-12-05 17:04 UTC, tellypresence commented
@kimkulling Any thoughts on the Sonar Cloud issues outlined above?

2024-12-26 18:10 UTC, kimkulling requested changes

2024-12-27 16:08 UTC, tellypresence commented on code/AssetLib/VRML/VrmlConverter.cpp
> +using std::string;
Removed "using" decl

2024-12-27 16:09 UTC, tellypresence commented on code/AssetLib/X3D/X3DImporter.cpp
> +#include "../VRML/VrmlConverter.hpp"
Replaced relative path

2024-12-27 16:09 UTC, tellypresence commented on code/AssetLib/X3D/X3DImporter.cpp
> +        return;
Added log statement

2024-12-28 20:23 UTC, kimkulling requested changes
Take a look into the sonarcube hint: use std::string_view instead of std::string.

2024-12-28 21:57 UTC, tellypresence commented
> Take a look into the sonarcube hint: use std::string_view instead of std::string.

`std::string_view` is a C++17 feature, is it OK to use it?  Here's a line in [`FBXConverter.cpp`](https://github.com/assimp/assimp/blob/7bd54e360450d2fbff5fe7e3a97ccfe6fdb04570/code/AssetLib/FBX/FBXConverter.cpp#L221) which notes that `std::string_view` would be an improvement but continues to use `std::string` to avoid causing problems for users with older build systems

2024-12-30 10:18 UTC, kimkulling commented
I will merge this PR and take care of the sonarcube findings. Great work!

2024-12-30 10:56 UTC, merged